const {chromium}=require('C:/Users/Vishnu saran/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
(async()=>{
 const b=await chromium.launch({channel:'chrome',headless:true});
 const p=await b.newPage({viewport:{width:1440,height:900}});
 const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await p.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});
 await p.locator('.hero-kenko [data-renderer="webgl"]').waitFor({timeout:30000});
 await p.waitForTimeout(1000);
 await p.screenshot({path:'screenshots/landing-hero-desktop.png'});
 await p.locator('.product-portal').scrollIntoViewIfNeeded();
 await p.getByRole('button',{name:'Complete check-in',exact:true}).waitFor();
 await p.waitForTimeout(1000);
 await p.screenshot({path:'screenshots/landing-product-desktop.png'});
 await p.getByRole('tab',{name:'Coach',exact:true}).click();
 await p.getByText('TODAY’S MOVEMENT PLAN',{exact:true}).waitFor();
 await p.getByRole('tab',{name:'Today',exact:true}).click();
 await p.getByRole('button',{name:'Complete check-in',exact:true}).waitFor();
 await p.waitForTimeout(800);
 await p.evaluate(()=>scrollTo(0,0));
 await p.waitForTimeout(600);
 await p.screenshot({path:'screenshots/landing-desktop-full.png',fullPage:true});
 await p.setViewportSize({width:390,height:844});
 await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(800);
 await p.screenshot({path:'screenshots/landing-hero-mobile.png'});
 await p.locator('.product-portal').evaluate(el=>el.scrollIntoView({block:'start'}));
 await p.waitForTimeout(1000);await p.screenshot({path:'screenshots/landing-product-mobile.png'});
 await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(500);
 await p.screenshot({path:'screenshots/landing-mobile-full.png',fullPage:true});
 if(errors.length)throw Error(JSON.stringify(errors));
 fs.writeFileSync('screenshots/production-smoke.json',JSON.stringify({url:'http://127.0.0.1:4173/',liveGLB:true,productTabs:true,errors},null,2));
 await b.close();console.log('Production preview, live GLB and product tabs passed; clean screenshots saved.');
})().catch(e=>{console.error(e);process.exit(1)});
