import { useEffect, useRef, useState } from 'react';
import { motion, useReducedMotion, useScroll, useMotionValueEvent } from 'framer-motion';
import { KenkoStage } from './KenkoStage';
import type { SceneMode } from './KenkoStage';
import { CheckinControls, Score } from './ProductPortal';
import { Icon } from './Icon';
import { deriveDay } from '../lib/content';
import type { Checkin, Signal } from '../lib/content';
const chapters:{title:string;label:string;text:string;mode:SceneMode;signal:Signal|null;color:string}[]=[
 {title:'SEE THE\nWHOLE YOU.',label:'01 / THE CONNECTED PICTURE',text:'Sleep, mood, movement, meals, water and recovery. Separate habits become one complete picture.',mode:'whole',signal:null,color:'#e2e8f7'},
 {title:'HOW DO\nYOU FEEL?',label:'02 / A MOMENT FOR YOURSELF',text:'A little context turns today’s sleep, energy, mood, stress and hydration into a practical next step.',mode:'checkin',signal:'Hydration',color:'#e5e4f1'},
 {title:'EAT WITH\nINTENTION.',label:'03 / EVERYDAY NOURISHMENT',text:'Real preferences. Familiar ingredients. Good food that fits the life you’re actually living.',mode:'nutrition',signal:'Nutrition',color:'#f1e3df'},
 {title:'MOVE FOR\nTODAY.',label:'04 / YOUR PACE, YOUR DAY',text:'Some days call for strength. Others, a little gentleness. Your plan should know the difference.',mode:'movement',signal:'Movement',color:'#e2ece5'},
 {title:'BETTER DAYS,\nBUILT GENTLY.',label:'05 / THE SMALL THINGS ADD UP',text:'A glass of water. A good night. A small walk. Your everyday actions become a rhythm you can build on.',mode:'complete',signal:null,color:'#e9e9dc'},
];
export function ScrollStory({value,setValue}:{value:Checkin;setValue:(v:Checkin)=>void}){
 const ref=useRef<HTMLElement>(null);const [chapter,setChapter]=useState(0);const [mobile,setMobile]=useState(()=>matchMedia('(max-width:700px)').matches);const reduced=useReducedMotion();const [phase,setPhase]=useState(0);
 const {scrollYProgress}=useScroll({target:ref,offset:['start start','end end']});useMotionValueEvent(scrollYProgress,'change',v=>setPhase(Math.round(v*20)/20));
 useEffect(()=>{const media=matchMedia('(max-width:700px)');const change=()=>setMobile(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{const obs=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setChapter(Number((e.target as HTMLElement).dataset.chapter));},{rootMargin:'-25% 0px -45% 0px',threshold:0});ref.current?.querySelectorAll('[data-chapter]').forEach(e=>obs.observe(e));return()=>obs.disconnect();},[]);
 const current=chapters[chapter],day=deriveDay(value);
 return <section id="story" ref={ref} className={`scroll-story ${reduced?'motion-reduced':''}`} style={{background:current.color}} aria-label="The connected wellness story"><div className="story-kicker"><span>FIVE SIGNALS. ONE WHOLE YOU.</span><span>EXPLORE AT YOUR OWN PACE</span></div><div className="story-layout">{!mobile&&<div className="story-visual"><div className="scene-number">0{chapter+1}<span> / 05</span></div><KenkoStage mode={current.mode} selected={current.signal} spread={chapter===0?Math.max(.55,1-phase):0}/><div className="story-scene-caption">{current.mode==='whole'?'YOUR HABITS, CONNECTED AT THE HEART.':current.mode==='checkin'?'A LITTLE CONTEXT CHANGES THE PICTURE.':current.mode==='nutrition'?'NOURISHMENT THAT FITS YOUR LIFE.':current.mode==='movement'?'PROGRESS AT YOUR OWN PACE.':'STEADY STEPS. A MORE CONNECTED YOU.'}</div><nav className="story-dots" aria-label="Wellness chapters">{chapters.map((c,i)=><a key={c.mode} href={`#chapter-${i}`} aria-label={c.title.replace('\n',' ')} aria-current={i===chapter?'step':undefined}><span/></a>)}</nav></div>}<div className="story-copy-column">{chapters.map((c,i)=><motion.article initial={false} whileInView={{opacity:1}} viewport={{once:true,amount:.2}} key={c.mode} id={`chapter-${i}`} data-chapter={i} className="story-chapter"><p className="eyebrow">{c.label}</p><h2>{c.title.split('\n').map((line,j)=><span key={line}>{j>0&&<br/>}{line}</span>)}</h2>{mobile&&<div className="mobile-story-scene"><KenkoStage mode={c.mode} selected={c.signal} spread={i===0?.8:0}/></div>}<p className="chapter-message">{c.text}</p>{i===0&&<div className="connected-signals"><span>Sleep</span><span>Move</span><span>Eat</span><span>Hydrate</span><span>Recover</span></div>}{i===1&&<div className="story-checkin"><div className="checkin-heading"><div><p className="eyebrow">A LIVE LITTLE CHECK-IN</p><p>Start where you are.</p></div><Score small value={day.score}/></div><CheckinControls compact value={value} onChange={setValue}/><p className="demo-note">Illustrative score. Try the controls and watch your movement plan adapt.</p></div>}{i===2&&<div className="story-result"><Icon name="food" size={26}/><div><h3>South Indian Protein Bowl</h3><p>28 g protein · 520 kcal · 20 min</p><small>Example meal · Estimated nutrition</small></div></div>}{i===3&&<div className="story-result" aria-live="polite"><Icon name="activity" size={26}/><div><h3>{day.recovery?'15-minute mobility':'30-minute strength'}</h3><p>{day.recovery?'A gentler plan for your check-in.':'Comfortable movement, at your pace.'}</p></div></div>}{i===4&&<><div className="story-week" aria-label="Example seven-day progress">{['M','T','W','T','F','S','S'].map((d,j)=><span key={j}><i><Icon name="check" size={14}/></i>{d}</span>)}</div><a className="text-button" href="#experience">Step into your day <Icon name="arrow" size={17}/></a></>}</motion.article>)}</div></div></section>;
}
