from pathlib import Path
p=Path('src/App.tsx');s=p.read_text(encoding='utf-8-sig');s=s.replace("import { asset }", "import { asset, navigation, siteConfig }")
s=s.replace("import { ProductPortal } from './components/ProductPortal';", "import { ProductPortal } from './components/ProductPortal';\nimport { FinalSections } from './components/FinalSections';\nimport { Dialog } from './components/Dialog';")
s=s.replace("const [menu,setMenu]=useState(false),[message,setMessage]=useState('');", "const [menu,setMenu]=useState(false),[modal,setModal]=useState('');\n const followLink=(e:React.MouseEvent<HTMLDivElement>)=>{const a=(e.target as HTMLElement).closest('a');if(!a)return;const href=a.getAttribute('href');if(href&&['#access','#privacy','#terms','#support'].includes(href)){e.preventDefault();setModal(href.slice(1));}setMenu(false);};")
s=s.replace('return <><header', 'return <div onClick={followLink}><a className="skip-link" href="#main">Skip to content</a><header')
a=s.index("{['Experience','Coach'");b=s.index('</nav>',a)
s=s[:a]+'''{navigation.map(n=><a key={n.label} href={n.href}>{n.label}</a>)}'''+s[b:]
a=s.index('<button className="login"');b=s.index('<button className="menu"',a)
s=s[:a]+'''<a className="login" href={siteConfig.routes.login}>Log in</a><a className="button dark" href={siteConfig.routes.signup}>Start free <Icon name="arrow" size={16}/></a>'''+s[b:]
s=s.replace('<main id="top">','<main id="main"><div id="top"/>')
a=s.index('<div className="hero-actions">');b=s.index('</div></div><div className="hero-note">',a)
s=s[:a]+'''<div className="hero-actions"><a className="button dark" href={siteConfig.routes.demo}>Meet KenkoBuddy <Icon name="arrow" size={19}/></a><a className="text-button" href={siteConfig.routes.story}>Explore the experience <Icon name="down" size={16}/></a>'''+s[b:]
s=s.replace('<ProductPortal value={value} setValue={setValue}/></main>', '<ProductPortal value={value} setValue={setValue}/><FinalSections/></main>')
a=s.index('{message&&')
s=s[:a]+'''{modal&&<Dialog title={modal==='access'?'Meet your next good day.':modal==='privacy'?'Your demo, your device.':modal==='terms'?'About this experience.':'Contact KenkoBuddy'} onClose={()=>setModal('')}>{modal==='access'?<><p>This standalone experience is ready to connect to KenkoBuddy. Login and account creation become available when the app’s destinations are configured.</p><a className="button dark" href={siteConfig.routes.demo} onClick={()=>setModal('')}>Explore the demo <Icon name="arrow"/></a></>:modal==='privacy'?<><p>Your check-ins, conversations, memory preferences and workout activity stay in this page. Reloading resets them. No real AI service or account database is connected.</p><p>The production app’s privacy policy has not been connected to this standalone experience.</p></>:modal==='terms'?<><p>This is an interactive product demonstration. Scores, meal estimates and progress examples are illustrative. No account is created.</p><p>{siteConfig.disclaimer}</p></>:<p>A support destination has not been connected yet. The project owner can set it in the centralized integration configuration.</p>}</Dialog>}</div>;\n}\n'''
p.write_text(s,encoding='utf-8')
p=Path('src/components/ProductPortal.tsx');s=p.read_text(encoding='utf-8-sig');s=s.replace("const refs=useRef<(HTMLButtonElement|null)[]>([]);", "useEffect(()=>{const update=()=>{if(location.hash==='#progress')setTab('Progress');};update();window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);\n const refs=useRef<(HTMLButtonElement|null)[]>([]);")
s=s.replace('<section id="experience" className="experience section-pad"><div', '<section id="experience" className="experience section-pad"><span id="progress" className="anchor-marker"/><div');p.write_text(s,encoding='utf-8')
